# Generated by Django 5.2.2 on 2025-07-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_phoneverification_profile'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugsale',
            name='prescription_id',
        ),
        migrations.AddField(
            model_name='drugsale',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_sales', to='patients.prescription'),
        ),
    ]
