# Generated by Django 5.2.2 on 2025-07-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_phoneverification_profile'),
        ('pharmacy', '0003_inventorylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'دارو', 'verbose_name_plural': 'داروها'},
        ),
        migrations.AlterModelOptions(
            name='druginventory',
            options={'verbose_name': 'موجودی دارو', 'verbose_name_plural': 'موجودی داروها'},
        ),
        migrations.AlterModelOptions(
            name='drugpurchase',
            options={'verbose_name': 'خرید دارو', 'verbose_name_plural': 'خریدهای دارو'},
        ),
        migrations.AlterModelOptions(
            name='drugsale',
            options={'verbose_name': 'فروش دارو', 'verbose_name_plural': 'فروش\u200cهای دارو'},
        ),
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'verbose_name': 'تاریخچه موجودی', 'verbose_name_plural': 'تاریخچه\u200cهای موجودی'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'verbose_name': 'آیتم نسخه', 'verbose_name_plural': 'آیتم\u200cهای نسخه'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'تامین\u200cکننده', 'verbose_name_plural': 'تامین\u200cکنندگان'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام دارو'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='druginventory',
            name='drug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='druginventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='druginventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='drugpurchase',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='drugpurchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='drugpurchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='drugpurchase',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='drugpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام بیمار'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_sales', to='patients.prescription', verbose_name='نسخه'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='drugsale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('purchase', 'خرید'), ('sale', 'فروش'), ('manual', 'اصلاح دستی')], max_length=20, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='note',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='دستور مصرف'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='prescription_id',
            field=models.IntegerField(verbose_name='کد نسخه'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='اطلاعات تماس'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام تامین\u200cکننده'),
        ),
    ]
