# Generated by Django 5.2.2 on 2025-11-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_payment_status'),
        ('pharmacy', '0005_drugpurchase_interval_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='medication_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_drug', to='patients.medicationtype', verbose_name='نوع دارو (بخش نسخه نویسی)'),
        ),
    ]
