# Generated by Django 5.2.2 on 2025-11-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_drug_medication_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='medication_type',
        ),
    ]
