# Generated by Django 5.2.2 on 2025-06-14 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_update_default_doses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('service_type', models.CharField(choices=[('drug', 'دارو'), ('visit', 'ویزیت'), ('lab', 'آزمایش'), ('other', 'سایر')], max_length=20, verbose_name='نوع خدمت')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_period',
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='dose',
            field=models.CharField(blank=True, choices=[('5mg', '۵mg'), ('20mg', '۲۰mg'), ('40mg', '۴۰mg'), ('82mg', '۸۲mg'), ('82/8', '۸۲/۸'), ('0.4', '۰/۴')], max_length=10, null=True, verbose_name='دوز مصرفی'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='امضاء دریافت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خدمت')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='تعداد/مقدار')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='هزینه کل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'تراکنش خدمت',
                'verbose_name_plural': 'تراکنش\u200cهای خدمات',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='patients.servicetransaction', verbose_name='تراکنش\u200cهای مرتبط'),
        ),
    ]
