# Generated by Django 5.2.2 on 2025-07-09 19:32

from django.db import migrations, models
import django.db.models.deletion


def set_default_medication_type(apps, schema_editor):
    """Set a default medication type for existing DrugQuota records"""
    DrugQuota = apps.get_model('patients', 'DrugQuota')
    MedicationType = apps.get_model('patients', 'MedicationType')
    
    # Get or create a default medication type
    default_type, _ = MedicationType.objects.get_or_create(
        name='داروی پیش‌فرض',
        defaults={
            'unit': 'عدد',
            'description': 'نوع داروی پیش‌فرض برای سهمیه‌های موجود'
        }
    )
    
    # Update all existing DrugQuota records to use the default type
    DrugQuota.objects.update(medication_type=default_type)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_create_alert_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugquota',
            name='medication_type',
            field=models.ForeignKey(
                'MedicationType',
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                verbose_name='نوع دارو',
                related_name='patient_quotas'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_default_medication_type,
            # No reverse code needed as this is a data migration
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='drugquota',
            name='medication_type',
            field=models.ForeignKey(
                'MedicationType',
                on_delete=django.db.models.deletion.PROTECT,
                verbose_name='نوع دارو',
                related_name='patient_quotas'
            ),
        ),
    ]
