# Generated by Django 5.2.6 on 2025-09-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_add_total_quota'),
        ('patients', '0021_final_migration'),
    ]

    operations = [
    ]
