# Generated by Django 5.1.7 on 2025-09-13 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تامین\u200cکننده')),
                ('contact_info', models.TextField(blank=True, verbose_name='اطلاعات تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو')),
            ],
            options={
                'verbose_name': 'موجودی دارو',
                'verbose_name_plural': 'موجودی داروها',
            },
        ),
        migrations.CreateModel(
            name='DrugSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فروش')),
                ('patient_name', models.CharField(blank=True, max_length=255, verbose_name='نام بیمار')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_sales', to='patients.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'فروش دارو',
                'verbose_name_plural': 'فروش\u200cهای دارو',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('purchase', 'خرید'), ('sale', 'فروش'), ('manual', 'اصلاح دستی')], max_length=20, verbose_name='نوع عملیات')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_inventory_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه موجودی',
                'verbose_name_plural': 'تاریخچه\u200cهای موجودی',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.IntegerField(verbose_name='کد نسخه')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('instructions', models.TextField(blank=True, verbose_name='دستور مصرف')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو')),
            ],
            options={
                'verbose_name': 'آیتم نسخه',
                'verbose_name_plural': 'آیتم\u200cهای نسخه',
            },
        ),
        migrations.CreateModel(
            name='DrugPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق خرید')),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه زمانی دریافت (روز)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ کل خرید')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='دارو')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'خرید دارو',
                'verbose_name_plural': 'خریدهای دارو',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier', verbose_name='تامین\u200cکننده'),
        ),
    ]
