# Generated by Django 5.2.2 on 2025-07-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_drug_options_alter_druginventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugpurchase',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بازه زمانی دریافت (روز)'),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='purchase_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق خرید'),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ کل خرید'),
        ),
    ]
