# Generated by Django 5.2.2 on 2025-06-07 19:02

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('suggestion', 'پیشنهاد'), ('complaint', 'انتقاد'), ('praise', 'تعریف و تمجید')], default='suggestion', max_length=20, verbose_name='نوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیشنهاد',
                'verbose_name_plural': 'پیشنهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('unit', models.CharField(help_text='مثال: میلی\u200cگرم، قرص', max_length=50, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'نوع دارو',
                'verbose_name_plural': 'انواع دارو',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('file_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='شماره پرونده')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('date_birth', django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'همسر فوت شده')], max_length=50, verbose_name='وضعیت تأهل')),
                ('education', models.CharField(choices=[('illiterate', 'بی\u200cسواد'), ('elementary', 'ابتدایی'), ('middle_school', 'راهنمایی'), ('high_school', 'دبیرستان'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا')], default='Unknown', max_length=100, verbose_name='تحصیلات')),
                ('drug_type', models.CharField(blank=True, choices=[('opium', 'تریاک'), ('heroin', 'هروئین'), ('meth', 'شیشه'), ('other', 'سایر')], max_length=100, null=True, verbose_name='نوع ماده مصرفی')),
                ('treatment_type', models.CharField(choices=[('maintenance', 'نگهدارنده'), ('detox', 'سم\u200cزدایی'), ('other', 'سایر')], max_length=100, verbose_name='نوع درمان')),
                ('usage_duration', models.CharField(max_length=50, verbose_name='مدت مصرف')),
                ('admission_date', django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ پذیرش')),
                ('treatment_withdrawal_date', django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ خروج از درمان')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='حل شده')),
            ],
            options={
                'verbose_name': 'پشتیبانی',
                'verbose_name_plural': 'پشتیبانی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=10, help_text='هشدار زمانی که موجودی به این مقدار برسد', max_digits=10, verbose_name='حداقل موجودی')),
                ('last_updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('medication_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='patients.medicationtype', verbose_name='نوع دارو')),
            ],
            options={
                'verbose_name': 'موجودی دارو',
                'verbose_name_plural': 'موجودی داروها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('payment_type', models.CharField(choices=[('visit', 'ویزیت'), ('medication', 'دارو'), ('other', 'سایر')], max_length=20, verbose_name='نوع پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_dose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='دوز روزانه')),
                ('treatment_duration', models.IntegerField(verbose_name='مدت درمان (روز)')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('total_prescribed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار کل تجویز شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('medication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.medicationtype', verbose_name='نوع دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MedicationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', django_jalali.db.models.jDateField(verbose_name='تاریخ توزیع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='باقی\u200cمانده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'توزیع دارو',
                'verbose_name_plural': 'توزیع داروها',
            },
        ),
    ]
