# Generated by Django 5.2.2 on 2025-06-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_payment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('pos', 'کارتخوان (POS)'), ('cash', 'نقد'), ('online', 'آنلاین (درگاه پرداخت)'), ('transfer', 'کارت به کارت'), ('other', 'سایر')], default='pos', max_length=20, verbose_name='نوع پرداخت'),
        ),
    ]
