# Generated by Django 5.2.2 on 2025-07-05 20:17

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_phoneverification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=django_jalali.db.models.jDateField(blank=True, help_text='مثال: 1402/01/01`', null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_start_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='مثال: 1402/01/01', null=True, verbose_name='تاریخ شروع درمان'),
        ),
    ]
