# Generated by Django 5.2.2 on 2025-07-23 21:06

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_add_quota_fields_and_dispense_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='تشخیص پزشکی'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پزشک معالج'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد نظام پزشکی'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('emergency', 'اورژانسی'), ('chronic', 'مزمن'), ('temporary', 'موقت')], default='normal', max_length=20, verbose_name='نوع نسخه'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=10, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات و دستورات'),
        ),
    ]
