# Generated by Django 5.2.2 on 2025-06-16 23:44

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='تاریخ نوبت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوبت دارویی',
                'verbose_name_plural': 'نوبت‌های دارویی',
            },
        ),
        migrations.CreateModel(
            name='DrugQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سهمیه دارویی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع سهمیه')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان سهمیه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سهمیه دارویی',
                'verbose_name_plural': 'سهمیه‌های دارویی',
            },
        ),
        migrations.CreateModel(
            name='DrugReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='تاریخ دریافت')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار دریافتی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'رسید دارویی',
                'verbose_name_plural': 'رسیدهای دارویی',
            },
        ),
    ]
