# Generated by Django 5.2.6 on 2025-09-08 19:19

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_inventorylog_alter_drugquota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=django_jalali.db.models.jDateField(blank=True, help_text='مثال: 1402/01/01', null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(help_text='شماره پرونده بیمار (فقط عدد)', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, help_text='به صورت خودکار از کد ملی تولید می\u200cشود', max_length=6, null=True, unique=True, verbose_name='کد بیمار'),
        ),
    ]
