# Generated by Django 5.2.6 on 2025-09-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_alter_patient_date_birth_alter_patient_file_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='سن'),
        ),
    ]
