# Generated by Django 4.2.11 on 2025-05-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('file_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پرونده')),
                ('system_code', models.CharField(max_length=20, verbose_name='کد سامانه')),
                ('drug_type', models.CharField(max_length=100, verbose_name='نوع دارو')),
                ('treatment_period', models.CharField(max_length=50, verbose_name='دوره دارویی')),
                ('th', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='T.H.')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='هزینه دریافتی')),
                ('payment_method', models.CharField(choices=[('نقدی', 'نقدی'), ('کارت', 'کارت'), ('سایر', 'سایر')], max_length=20, verbose_name='نوع پرداخت')),
                ('signature', models.BooleanField(default=False, verbose_name='امضا')),
                ('admission_date', models.DateField(auto_now_add=True, verbose_name='تاریخ پذیرش')),
            ],
            options={
                'db_table': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_40mg', models.IntegerField(verbose_name='دوز ۴۰mg')),
                ('dosage_20mg', models.IntegerField(verbose_name='دوز ۲۰mg')),
                ('dosage_5mg', models.IntegerField(verbose_name='دوز ۵mg')),
                ('patient', models.ForeignKey(db_column='شماره_پرونده', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'داروها',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_count', models.IntegerField(verbose_name='تعداد اعضا')),
                ('support_type', models.CharField(max_length=50, verbose_name='نوع حمایت')),
                ('recorded_deviations', models.TextField(verbose_name='انحرافات ثبت شده')),
                ('patient', models.ForeignKey(db_column='شماره_پرونده', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'خانواده',
            },
        ),
    ]
