# Generated by Django 5.2.1 on 2025-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "file_number",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="شماره پرونده",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="نام خانوادگی"),
                ),
                (
                    "national_code",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "date_birth",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "مرد"), ("female", "زن")],
                        max_length=10,
                        null=True,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "marital_status",
                    models.CharField(max_length=50, verbose_name="وضعیت تأهل"),
                ),
                (
                    "education",
                    models.CharField(
                        default="Unknown", max_length=100, verbose_name="تحصیلات"
                    ),
                ),
                (
                    "drug_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نوع ماده مصرفی",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(max_length=100, verbose_name="نوع درمان"),
                ),
                (
                    "usage_duration",
                    models.CharField(max_length=50, verbose_name="مدت مصرف"),
                ),
                (
                    "admission_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پذیرش"),
                ),
                (
                    "treatment_withdrawal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ خروج از درمان"
                    ),
                ),
            ],
        ),
    ]
