# Generated by Django 5.2.1 on 2025-05-24 18:02

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ پذیرش"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_birth",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="treatment_withdrawal_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ خروج از درمان"
            ),
        ),
    ]
