# Generated by Django 5.2.1 on 2025-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='ردیف '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='  شماره پرونده نام و نام خانوادگی '),
        ),
    ]
