# Generated by Django 5.2.1 on 2025-05-20 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_file_number_alter_patient_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='drug_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment_period',
        ),
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_0_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='دوز 0.4'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_20mg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='دوز 20mg'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_40mg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='دوز 40mg'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_5mg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='دوز 5mg'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_b2_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='B2 ۱'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_b2_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='B2 ۲'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dose_b2_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='B2 ۳'),
        ),
        migrations.AddField(
            model_name='patient',
            name='receiver_signature',
            field=models.CharField(default='Dr. Unknown', max_length=100, verbose_name='امضاء دریافت\u200cکننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ردیف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(max_length=50, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_amount',
            field=models.BigIntegerField(verbose_name='هزینه پرداختی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='system_code',
            field=models.CharField(max_length=50, verbose_name='کد سامانه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='th',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='T.H'),
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
