# Generated by Django 5.2.1 on 2025-05-26 15:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_admission_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "بیمار", "verbose_name_plural": "بیماران"},
        ),
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="مثال: ۱۴۰۲/۰۱/۰۱",
                null=True,
                verbose_name="تاریخ پذیرش",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_birth",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="مثال: ۱۴۰۲/۰۱/۰۱",
                null=True,
                verbose_name="تاریخ تولد",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="treatment_withdrawal_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="مثال: ۱۴۰۲/۰۱/۰۱",
                null=True,
                verbose_name="تاریخ خروج از درمان",
            ),
        ),
    ]
