# Generated by Django 5.2.1 on 2025-05-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceAbuseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_number', models.CharField(max_length=100, verbose_name='شماره پرونده')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('age_patient', models.CharField(max_length=100, verbose_name='سن')),
                ('age_of_onset', models.PositiveIntegerField(verbose_name='سن شروع مصرف')),
                ('address_numberphone', models.TextField(verbose_name='آدرس و ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
