# Generated by Django 5.2.1 on 2025-05-26 15:48

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0003_alter_patient_options_alter_patient_admission_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام دارو")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="مثال: میلی\u200cگرم، قرص",
                        max_length=50,
                        verbose_name="واحد",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع دارو",
                "verbose_name_plural": "انواع دارو",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("visit", "ویزیت"),
                            ("medication", "دارو"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_dose",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="دوز روزانه"
                    ),
                ),
                (
                    "treatment_duration",
                    models.IntegerField(verbose_name="مدت درمان (روز)"),
                ),
                (
                    "start_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پایان"),
                ),
                (
                    "total_prescribed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="مقدار کل تجویز شده",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت\u200cها"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "medication_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.medicationtype",
                        verbose_name="نوع دارو",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخه",
                "verbose_name_plural": "نسخه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="MedicationDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ توزیع"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مقدار"
                    ),
                ),
                (
                    "remaining",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="باقی\u200cمانده"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت\u200cها"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.prescription",
                        verbose_name="نسخه",
                    ),
                ),
            ],
            options={
                "verbose_name": "توزیع دارو",
                "verbose_name_plural": "توزیع داروها",
            },
        ),
    ]
