# Generated by Django 5.2.1 on 2025-05-28 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_medicationtype_payment_prescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="drug_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opium", "تریاک"),
                    ("heroin", "هروئین"),
                    ("meth", "شیشه"),
                    ("other", "سایر"),
                ],
                max_length=100,
                null=True,
                verbose_name="نوع ماده مصرفی",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="education",
            field=models.CharField(
                choices=[
                    ("illiterate", "بی\u200cسواد"),
                    ("elementary", "ابتدایی"),
                    ("middle_school", "راهنمایی"),
                    ("high_school", "دبیرستان"),
                    ("diploma", "دیپلم"),
                    ("associate", "فوق دیپلم"),
                    ("bachelor", "لیسانس"),
                    ("master", "فوق لیسانس"),
                    ("phd", "دکترا"),
                ],
                default="Unknown",
                max_length=100,
                verbose_name="تحصیلات",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "مجرد"),
                    ("married", "متأهل"),
                    ("divorced", "مطلقه"),
                    ("widowed", "همسر فوت شده"),
                ],
                max_length=50,
                verbose_name="وضعیت تأهل",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="treatment_type",
            field=models.CharField(
                choices=[
                    ("maintenance", "نگهدارنده"),
                    ("detox", "سم\u200cزدایی"),
                    ("other", "سایر"),
                ],
                max_length=100,
                verbose_name="نوع درمان",
            ),
        ),
    ]
