# Generated by Django 5.2.2 on 2025-07-09 19:20

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_fix_models'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('prescription_expiry', 'انقضای نسخه'), ('low_stock', 'موجودی کم'), ('quota_warning', 'هشدار سهمیه'), ('appointment', 'نوبت ویزیت'), ('other', 'سایر')], max_length=50, verbose_name='نوع هشدار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هشدار')),
                ('message', models.TextField(verbose_name='پیام هشدار')),
                ('related_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل مرتبط')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه رکورد مرتبط')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='اولویت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('alert_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ هشدار')),
                ('due_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ موعد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدارها',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_read'], name='patients_al_alert_t_3f9f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['related_model', 'related_id'], name='patients_al_related_1d6e20_idx'),
        ),
    ]
