# Generated by Django 5.2.2 on 2025-06-11 21:51

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دارو')),
                ('unit', models.CharField(help_text='مثال: قرص، میلی\u200cلیتر، گرم', max_length=50, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='کد بیمار'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_start_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ شروع درمان'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_period',
            field=models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('semi_annually', 'شش ماهه'), ('annually', 'سالانه'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دوره پرداخت'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255, verbose_name='وضعیت پزشکی')),
                ('diagnosis_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تشخیص')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه پزشکی',
                'verbose_name_plural': 'سوابق پزشکی',
            },
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_files/', verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'فایل بیمار',
                'verbose_name_plural': 'فایل\u200cهای بیماران',
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار اولیه')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار فعلی')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تخصیص')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medication', verbose_name='دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'داروی بیمار',
                'verbose_name_plural': 'داروهای بیماران',
                'unique_together': {('patient', 'medication')},
            },
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار توزیع شده')),
                ('dispensing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ توزیع')),
                ('patient_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmedication', verbose_name='داروی تخصیص یافته به بیمار')),
            ],
            options={
                'verbose_name': 'رکورد توزیع دارو',
                'verbose_name_plural': 'رکوردهای توزیع دارو',
                'ordering': ['-dispensing_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'برنامه درمانی',
                'verbose_name_plural': 'برنامه\u200cهای درمانی',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان ویزیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ویزیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-visit_date'],
            },
        ),
    ]
