# Generated by Django 5.2.2 on 2025-06-13 20:46
from django.db import migrations

def add_medications(apps, schema_editor):
    MedicationType = apps.get_model('patients', 'MedicationType')
    
    medications_to_add = [
        {'name': 'شربت اپیوم', 'unit': 'سی سی'},
        {'name': 'قرص بوپرنورفین 8 میلی گرم', 'unit': 'عدد'},
        {'name': 'قرص بوپرنورفین 2 میلی گرم', 'unit': 'عدد'},
        {'name': 'قرص بوپرنورفین 0.4 میلی گرم', 'unit': 'عدد'},
        {'name': 'قرص متادون 40 میلی گرم', 'unit': 'عدد'},
        {'name': 'قرص متادون 20 میلی گرم', 'unit': 'عدد'},
        {'name': 'قرص متادون 5 میلی گرم', 'unit': 'عدد'},
        {'name': 'شربت متادون', 'unit': 'سی سی'},
    ]

    for med_data in medications_to_add:
        MedicationType.objects.get_or_create(name=med_data['name'], defaults={'unit': med_data['unit']})

def remove_medications(apps, schema_editor):
    MedicationType = apps.get_model('patients', 'MedicationType')
    
    medication_names = [
        'شربت اپیوم',
        'قرص بوپرنورفین 8 میلی گرم',
        'قرص بوپرنورفین 2 میلی گرم',
        'قرص بوپرنورفین 0.4 میلی گرم',
        'قرص متادون 40 میلی گرم',
        'قرص متادون 20 میلی گرم',
        'قرص متادون 5 میلی گرم',
        'شربت متادون',
    ]

    MedicationType.objects.filter(name__in=medication_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medication_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_medications, reverse_code=remove_medications),
    ]
