# Generated by Django 5.2.2 on 2025-08-19 20:16

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_prescription_created_by_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='addiction_start_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='سن شروع اعتیاد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ تشکیل پرونده'),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='دوز')),
                ('dosage_unit', models.CharField(default='عدد', max_length=20, verbose_name='واحد دوز')),
                ('frequency', models.CharField(choices=[('qd', 'روزی یکبار'), ('bid', 'روزی دوبار'), ('tid', 'روزی سه بار'), ('qid', 'روزی چهار بار'), ('qod', 'یک روز در میان'), ('qwk', 'هفته\u200cای یک بار'), ('prn', 'در صورت نیاز')], default='bid', max_length=10, verbose_name='تعداد دفعات مصرف در روز')),
                ('route', models.CharField(choices=[('po', 'خوراکی'), ('sc', 'زیرجلدی'), ('im', 'عضلانی'), ('iv', 'وریدی'), ('topical', 'موضعی'), ('inhalation', 'استنشاقی'), ('rectal', 'مقعدی'), ('vaginal', 'واژینال'), ('otic', 'گوشی'), ('ophthalmic', 'چشمی')], default='po', max_length=15, verbose_name='راه مصرف')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان مصرف به روز', verbose_name='مدت مصرف (روز)')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='دستورات مصرف')),
                ('is_prn', models.BooleanField(default=False, help_text='در صورت لزوم مصرف شود', verbose_name='در صورت نیاز')),
                ('prn_instructions', models.TextField(blank=True, null=True, verbose_name='دستورالعمل مصرف در صورت نیاز')),
                ('start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع مصرف')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان مصرف')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.medicationtype', verbose_name='دارو')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='patients.prescription')),
            ],
            options={
                'verbose_name': 'آیتم نسخه',
                'verbose_name_plural': 'آیتم\u200cهای نسخه',
                'ordering': ['created_at'],
            },
        ),
    ]
