# Generated by Django 5.1.7 on 2025-09-13 18:56

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان نوبت')),
                ('status', models.CharField(choices=[('scheduled', 'رزرو شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
