# Generated by Django 5.1.7 on 2025-09-13 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('suggestion', 'پیشنهاد'), ('complaint', 'انتقاد'), ('praise', 'تعریف و تمجید')], default='suggestion', max_length=20, verbose_name='نوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیشنهاد',
                'verbose_name_plural': 'پیشنهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دارو')),
                ('unit', models.CharField(help_text='مثال: قرص، میلی\u200cلیتر، گرم', max_length=50, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('unit', models.CharField(help_text='مثال: میلی\u200cگرم، قرص', max_length=50, verbose_name='واحد')),
                ('default_dose', models.DecimalField(blank=True, decimal_places=2, help_text='دوز پیشنهادی برای نمایش در فرم نسخه', max_digits=10, null=True, verbose_name='دوز پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'نوع دارو',
                'verbose_name_plural': 'انواع دارو',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('file_number', models.CharField(blank=True, help_text='شماره پرونده به صورت خودکار تولید می\u200cشود', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='شماره پرونده')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('patient_code', models.CharField(blank=True, help_text='به صورت خودکار از کد ملی تولید می\u200cشود', max_length=6, null=True, unique=True, verbose_name='کد بیمار')),
                ('date_birth', django_jalali.db.models.jDateField(blank=True, help_text='مثال: 1402/01/01', null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن همراه')),
                ('phone_number_landline', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن ثابت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'همسر فوت شده')], max_length=50, verbose_name='وضعیت تأهل')),
                ('education', models.CharField(choices=[('illiterate', 'بی\u200cسواد'), ('elementary', 'ابتدایی'), ('middle_school', 'راهنمایی'), ('high_school', 'دبیرستان'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا')], default='Unknown', max_length=100, verbose_name='تحصیلات')),
                ('drug_type', models.CharField(blank=True, choices=[('opium', 'تریاک'), ('heroin', 'هروئین'), ('meth', 'شیشه'), ('other', 'سایر')], max_length=100, null=True, verbose_name='نوع ماده مصرفی')),
                ('treatment_type', models.CharField(choices=[('maintenance', 'نگهدارنده'), ('detox', 'سم\u200cزدایی'), ('other', 'سایر')], max_length=100, verbose_name='نوع درمان')),
                ('usage_duration', models.CharField(max_length=50, verbose_name='مدت مصرف')),
                ('admission_date', django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ پذیرش')),
                ('treatment_withdrawal_date', django_jalali.db.models.jDateField(blank=True, help_text='مثال: ۱۴۰۲/۰۱/۰۱', null=True, verbose_name='تاریخ خروج از درمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('addiction_start_age', models.PositiveSmallIntegerField(blank=True, help_text='سن شروع مصرف مواد مخدر (به سال)', null=True, verbose_name='سن شروع اعتیاد')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('service_type', models.CharField(choices=[('drug', 'دارو'), ('visit', 'ویزیت'), ('lab', 'آزمایش'), ('other', 'سایر')], max_length=20, verbose_name='نوع خدمت')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='حل شده')),
            ],
            options={
                'verbose_name': 'پشتیبانی',
                'verbose_name_plural': 'پشتیبانی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('payment', models.FloatField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.drugappointment')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=10, help_text='هشدار زمانی که موجودی به این مقدار برسد', max_digits=10, verbose_name='حداقل موجودی')),
                ('last_updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('medication_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='patients.medicationtype', verbose_name='نوع دارو')),
            ],
            options={
                'verbose_name': 'موجودی دارو',
                'verbose_name_plural': 'موجودی داروها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensing_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تحویل')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'مقدار باید بزرگتر از صفر باشد')], verbose_name='مقدار تحویلی')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'قیمت نمی\u200cتواند منفی باشد')], verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.DecimalField(decimal_places=0, editable=False, max_digits=15, verbose_name='جمع کل (ریال)')),
                ('dispensing_type', models.CharField(choices=[('normal', 'عادی'), ('emergency', 'اضطراری'), ('special', 'ویژه')], default='normal', max_length=20, verbose_name='نوع تحویل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('medication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensings', to='patients.medicationtype', verbose_name='نوع دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_dispensings', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'تحویل دارو',
                'verbose_name_plural': 'تحویل\u200cهای دارویی',
                'ordering': ['-dispensing_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تجویز')),
                ('dose', models.CharField(blank=True, choices=[('5mg', '۵mg'), ('20mg', '۲۰mg'), ('40mg', '۴۰mg'), ('82mg', '۸۲mg'), ('82/8', '۸۲/۸'), ('0.4', '۰/۴')], max_length=10, null=True, verbose_name='دوز مصرفی')),
                ('administered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مقدار تجویز شده')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه دریافتی (تومان)')),
                ('signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='امضاء دریافت\u200cکننده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medication', verbose_name='دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'تجویز دارو',
                'verbose_name_plural': 'تجویز داروها',
                'ordering': ['-administration_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255, verbose_name='وضعیت پزشکی')),
                ('diagnosis_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تشخیص')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه پزشکی',
                'verbose_name_plural': 'سوابق پزشکی',
            },
        ),
        migrations.AddField(
            model_name='drugappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_files/', verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'فایل بیمار',
                'verbose_name_plural': 'فایل\u200cهای بیماران',
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار اولیه')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار فعلی')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تخصیص')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medication', verbose_name='دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'داروی بیمار',
                'verbose_name_plural': 'داروهای بیماران',
                'unique_together': {('patient', 'medication')},
            },
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار توزیع شده')),
                ('dispensing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ توزیع')),
                ('patient_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmedication', verbose_name='داروی تخصیص یافته به بیمار')),
            ],
            options={
                'verbose_name': 'رکورد توزیع دارو',
                'verbose_name_plural': 'رکوردهای توزیع دارو',
                'ordering': ['-dispensing_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_dose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='دوز روزانه')),
                ('treatment_duration', models.IntegerField(verbose_name='مدت درمان (روز)')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('total_prescribed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار کل تجویز شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('medication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.medicationtype', verbose_name='نوع دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره موبایل')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تایید شده با موبایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خدمت')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='تعداد/مقدار')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='هزینه کل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'تراکنش خدمت',
                'verbose_name_plural': 'تراکنش\u200cهای خدمات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('pos', 'کارتخوان (POS)'), ('cash', 'نقد'), ('online', 'آنلاین (درگاه پرداخت)'), ('transfer', 'کارت به کارت'), ('other', 'سایر')], default='pos', max_length=20, verbose_name='نوع پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.prescription', verbose_name='نسخه مرتبط')),
                ('transactions', models.ManyToManyField(blank=True, to='patients.servicetransaction', verbose_name='تراکنش\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'برنامه درمانی',
                'verbose_name_plural': 'برنامه\u200cهای درمانی',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان ویزیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ویزیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('prescription_expiry', 'انقضای نسخه'), ('low_stock', 'موجودی کم'), ('quota_warning', 'هشدار سهمیه'), ('appointment', 'نوبت ویزیت'), ('other', 'سایر')], max_length=50, verbose_name='نوع هشدار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هشدار')),
                ('message', models.TextField(verbose_name='پیام هشدار')),
                ('related_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل مرتبط')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه رکورد مرتبط')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='اولویت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('alert_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ هشدار')),
                ('due_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ موعد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدارها',
                'ordering': ['-alert_date'],
                'indexes': [models.Index(fields=['alert_type', 'is_read'], name='patients_al_alert_t_fd7a17_idx'), models.Index(fields=['related_model', 'related_id'], name='patients_al_related_95ff26_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='مقدار مثبت برای افزایش و مقدار منفی برای کاهش موجودی', max_digits=10, verbose_name='تغییر مقدار')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی قبلی')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی جدید')),
                ('log_type', models.CharField(choices=[('purchase', 'خرید'), ('distribution', 'توزیع'), ('adjustment', 'تعدیل'), ('return', 'عودت'), ('waste', 'ضایعات')], max_length=20, verbose_name='نوع عملیات')),
                ('reference_type', models.CharField(help_text="نوع مدل مرجع (مانند 'medicationdistribution')", max_length=50, verbose_name='مرجع عملیات')),
                ('reference_id', models.PositiveIntegerField(help_text='شناسه رکورد مرجع', verbose_name='شناسه مرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_inventory_logs', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.druginventory', verbose_name='آیتم موجودی')),
            ],
            options={
                'verbose_name': 'لاگ موجودی',
                'verbose_name_plural': 'لاگ\u200cهای موجودی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item', 'created_at'], name='patients_in_invento_63dd59_idx'), models.Index(fields=['reference_type', 'reference_id'], name='patients_in_referen_3b20a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrugQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_quota', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'مقدار سهمیه باید بزرگتر از صفر باشد')], verbose_name='سهمیه ماهانه')),
                ('remaining_quota', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'سهمیه باقی\u200cمانده نمی\u200cتواند منفی باشد')], verbose_name='سهمیه باقی\u200cمانده')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع سهمیه')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان سهمیه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('medication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_quotas', to='patients.medicationtype', verbose_name='نوع دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_quotas', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سهمیه دارو',
                'verbose_name_plural': 'سهمیه\u200cهای دارویی',
                'ordering': ['-start_date', 'medication_type__name'],
                'indexes': [models.Index(fields=['patient', 'medication_type'], name='patients_dr_patient_233bae_idx'), models.Index(fields=['start_date', 'end_date'], name='patients_dr_start_d_ad06cf_idx'), models.Index(fields=['is_active'], name='patients_dr_is_acti_e73ac1_idx')],
                'unique_together': {('patient', 'medication_type', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='MedicationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', django_jalali.db.models.jDateField(verbose_name='تاریخ توزیع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'مقدار باید بزرگتر از صفر باشد')], verbose_name='مقدار')),
                ('remaining', models.DecimalField(decimal_places=2, editable=False, help_text='مقدار باقی\u200cمانده از نسخه پس از این توزیع', max_digits=10, verbose_name='باقی\u200cمانده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to=settings.AUTH_USER_MODEL, verbose_name='توزیع کننده')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='patients.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'توزیع دارو',
                'verbose_name_plural': 'توزیع\u200cهای دارویی',
                'ordering': ['-distribution_date', '-created_at'],
                'indexes': [models.Index(fields=['prescription'], name='patients_me_prescri_33a0ac_idx'), models.Index(fields=['distribution_date'], name='patients_me_distrib_2a00b5_idx'), models.Index(fields=['created_by'], name='patients_me_created_4add46_idx')],
            },
        ),
    ]
