# Generated by Django 5.2.2 on 2025-06-13 20:58

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_add_initial_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtype',
            name='default_dose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='دوز پیشنهادی برای نمایش در فرم نسخه', max_digits=10, null=True, verbose_name='دوز پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار'),
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تجویز')),
                ('administered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مقدار تجویز شده')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه دریافتی (تومان)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medication', verbose_name='دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'تجویز دارو',
                'verbose_name_plural': 'تجویز داروها',
                'ordering': ['-administration_date'],
            },
        ),
    ]
