# Generated by Django 5.2.2 on 2025-06-16 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_service_remove_payment_payment_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.prescription', verbose_name='نسخه مرتبط'),
        ),
    ]
