# Generated by Django 5.2.2 on 2025-07-10 22:00

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_add_monthly_quota_to_drugquota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='مقدار مثبت برای افزایش و مقدار منفی برای کاهش موجودی', max_digits=10, verbose_name='تغییر مقدار')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی قبلی')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی جدید')),
                ('log_type', models.CharField(choices=[('purchase', 'خرید'), ('distribution', 'توزیع'), ('adjustment', 'تعدیل'), ('return', 'عودت'), ('waste', 'ضایعات')], max_length=20, verbose_name='نوع عملیات')),
                ('reference_type', models.CharField(help_text="نوع مدل مرجع (مانند 'medicationdistribution')", max_length=50, verbose_name='مرجع عملیات')),
                ('reference_id', models.PositiveIntegerField(help_text='شناسه رکورد مرجع', verbose_name='شناسه مرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'لاگ موجودی',
                'verbose_name_plural': 'لاگ\u200cهای موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='drugquota',
            options={'ordering': ['-start_date', 'medication_type__name'], 'verbose_name': 'سهمیه دارو', 'verbose_name_plural': 'سهمیه\u200cهای دارویی'},
        ),
        migrations.AlterModelOptions(
            name='medicationdistribution',
            options={'ordering': ['-distribution_date', '-created_at'], 'verbose_name': 'توزیع دارو', 'verbose_name_plural': 'توزیع\u200cهای دارویی'},
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='patients_al_alert_t_fd7a17_idx',
            old_name='patients_al_alert_t_3f9f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='patients_al_related_95ff26_idx',
            old_name='patients_al_related_1d6e20_idx',
        ),
        migrations.AlterUniqueTogether(
            name='drugquota',
            unique_together={('patient', 'medication_type', 'start_date')},
        ),
        migrations.AddField(
            model_name='medicationdistribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to=settings.AUTH_USER_MODEL, verbose_name='توزیع کننده'),
        ),
        migrations.AlterField(
            model_name='drugquota',
            name='medication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_quotas', to='patients.medicationtype', verbose_name='نوع دارو'),
        ),
        migrations.AlterField(
            model_name='drugquota',
            name='monthly_quota',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'مقدار سهمیه باید بزرگتر از صفر باشد')], verbose_name='سهمیه ماهانه'),
        ),
        migrations.AlterField(
            model_name='drugquota',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_quotas', to='patients.patient', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='drugquota',
            name='remaining_quota',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'سهمیه باقی\u200cمانده نمی\u200cتواند منفی باشد')], verbose_name='سهمیه باقی\u200cمانده'),
        ),
        migrations.AlterField(
            model_name='medicationdistribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'مقدار باید بزرگتر از صفر باشد')], verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='medicationdistribution',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='patients.prescription', verbose_name='نسخه'),
        ),
        migrations.AlterField(
            model_name='medicationdistribution',
            name='remaining',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='مقدار باقی\u200cمانده از نسخه پس از این توزیع', max_digits=10, verbose_name='باقی\u200cمانده'),
        ),
        migrations.AddIndex(
            model_name='drugquota',
            index=models.Index(fields=['patient', 'medication_type'], name='patients_dr_patient_233bae_idx'),
        ),
        migrations.AddIndex(
            model_name='drugquota',
            index=models.Index(fields=['start_date', 'end_date'], name='patients_dr_start_d_ad06cf_idx'),
        ),
        migrations.AddIndex(
            model_name='drugquota',
            index=models.Index(fields=['is_active'], name='patients_dr_is_acti_e73ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdistribution',
            index=models.Index(fields=['prescription'], name='patients_me_prescri_33a0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdistribution',
            index=models.Index(fields=['distribution_date'], name='patients_me_distrib_2a00b5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdistribution',
            index=models.Index(fields=['created_by'], name='patients_me_created_4add46_idx'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_inventory_logs', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.druginventory', verbose_name='آیتم موجودی'),
        ),
        migrations.RemoveField(
            model_name='drugquota',
            name='total_quota',
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['inventory_item', 'created_at'], name='patients_in_invento_63dd59_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['reference_type', 'reference_id'], name='patients_in_referen_3b20a5_idx'),
        ),
    ]
